using System;

namespace SuperPowerEditor.Base.DataAccess.Entities
{
    public class Country
    {
        public int? MiliManpowerAvai { get; set; }
        public double? InflationLevelExpected { get; set; }
        public double? InflationLevel { get; set; }
        public double? InterestLevel { get; set; }
        public double? MinimumWage { get; set; }
        public double? GdpGrowth { get; set; }
        public int? PoliticalParty { get; set; }
        public int? NationalHoliday { get; set; }
        public int? GvtType { get; set; }
        public double? GvtStability { get; set; }
        public double? GvtStabilityEx { get; set; }
        public double? GvtApproval { get; set; }
        public double? GvtApprovalEx { get; set; }
        public double? EmigrationLevel { get; set; }
        public double? EmigrationLevelEx { get; set; }
        public string EmigrationClosed { get; set; }
        public double? ImmigrationLevel { get; set; }
        public string ImmigrationClosed { get; set; }
        public DateTime? NextElection { get; set; }
        public double? CorruptionLevel { get; set; }
        public double? CorruptionLevelEx { get; set; }
        public string MartialLaw { get; set; }
        public double? TelecomLevelEx { get; set; }
        public double? InfrastructureLevelEx { get; set; }
        public string LawFreedomSpeech { get; set; }
        public string LawFreedomDemonstration { get; set; }
        public string LawWomenSuffrage { get; set; }
        public string LawNbChildren { get; set; }
        public string LawContraception { get; set; }
        public string LawAbortion { get; set; }
        public string LawChildLabor { get; set; }
        public string LawPolygamy { get; set; }
        public string LawSameSexMarriage { get; set; }
        public double? NatSecurityLevel { get; set; }
        public double? AmdsLevel { get; set; }
        public double? NuclearReady { get; set; }
        public double? LastIteration { get; set; }
        public int? Id { get; set; }
        public int? NameStid { get; set; }
        public string Code { get; set; }
        public string Flag { get; set; }
        public int? CapitalId { get; set; }
        public int? Groups { get; set; }
        public string Activated { get; set; }
        public string AcceptForeignOrder { get; set; }
        public double? IndivCollec { get; set; }
        public double? HierDistance { get; set; }
        public double? MaleFemale { get; set; }
        public int? Climate { get; set; }
        public int? NaturalHazards { get; set; }
        public int? Terrain { get; set; }
        public double? Pop1565Unemployed { get; set; }
        public double? PopInPoverty { get; set; }
        public double? PopEconomicModel { get; set; }
        public double? PopPoliticalIdeology { get; set; }
        public double? BirthRate { get; set; }
        public double? DeathRate { get; set; }
        public double? BirthRateEx { get; set; }
        public double? DeathRateEx { get; set; }
        public double? HumanDevelopment { get; set; }
        public int? Suffrage { get; set; }
        public double? GlobalTaxMod { get; set; }
        public double? PersonalIncomeTax { get; set; }
        public double? AvailableMoney { get; set; }
        public double? EconomicActivity { get; set; }
        public double? EconomicHealth { get; set; }
        public double? BudgetExpenseUnitUpkeep { get; set; }
        public double? BudgetExpenseSecurity { get; set; }
        public double? BudgetExpenseDiplomacy { get; set; }
        public double? BudgetExpenseImports { get; set; }
        public double? BudgetExpenseRatioResearch { get; set; }
        public double? BudgetExpenseRatioInfra { get; set; }
        public double? BudgetExpenseRatioEnviron { get; set; }
        public double? BudgetExpenseRatioHealthcare { get; set; }
        public double? BudgetExpenseRatioEducation { get; set; }
        public double? BudgetExpenseRatioGovernment { get; set; }
        public double? BudgetExpenseRatioImf { get; set; }
        public double? BudgetExpenseRatioTelecom { get; set; }
        public double? BudgetExpenseRatioTourism { get; set; }
        public double? BudgetExpenseRatioPropaganda { get; set; }
        public double? BudgetExpenseCorruption { get; set; }
        public double? BudgetRevenueTax { get; set; }
        public double? BudgetRevenueExports { get; set; }
        public double? BudgetRevenueImf { get; set; }
        public double? BudgetRevenueTourism { get; set; }
        public double? PropagandaLevel { get; set; }
    }
}