namespace SuperPowerEditor.Base.DataAccess.Entities
{
    public class Region
    {
        public int? Id { get; set; }
        public int? RegionId { get; set; }
        public int? RegionName { get; set; }
        public int? CountryId { get; set; }
        public int? MilitaryOwnerId { get; set; }
        public int? GeoGroup { get; set; }
        public int? Continent { get; set; }
        public int? History { get; set; }
        public int? Population15 { get; set; }
        public int? Population1565 { get; set; }
        public int? Population65 { get; set; }
        public double? Infrastructure { get; set; }
        public double? TelecomLevel { get; set; }
        public double? TourismIncome { get; set; }
        public double? AreaWater { get; set; }
        public double? ArableLand { get; set; }
        public double? ForestLand { get; set; }
        public double? ParksLand { get; set; }
        public double? NotUsedLand { get; set; }
        public int? HighestPoint { get; set; }
        public int? LowestPoint { get; set; }
        public int? StandardElevation { get; set; }
        public int? Coastlines { get; set; }
        public double? CerealsProduction { get; set; }
        public double? VegFruitsProduction { get; set; }
        public double? MeatProduction { get; set; }
        public double? DairyProduction { get; set; }
        public double? TobaccoProduction { get; set; }
        public double? DrugsProduction { get; set; }
        public double? ElectricityProduction { get; set; }
        public double? FossileFuelsProduction { get; set; }
        public double? WoodProduction { get; set; }
        public double? MineralsProduction { get; set; }
        public double? IronSteelProduction { get; set; }
        public double? PrecStonesProduction { get; set; }
        public double? FabricsProduction { get; set; }
        public double? PlasticsProduction { get; set; }
        public double? ChemicalsProduction { get; set; }
        public double? PharmaProduction { get; set; }
        public double? HhApplProduction { get; set; }
        public double? VehiculesProduction { get; set; }
        public double? MachineryProduction { get; set; }
        public double? HhCommProduction { get; set; }
        public double? LuxuryCommProduction { get; set; }
        public double? ConstructionProduction { get; set; }
        public double? EngineeringProduction { get; set; }
        public double? HealthCareProduction { get; set; }
        public double? RetailProduction { get; set; }
        public double? LegalServProduction { get; set; }
        public double? MarketAdProduction { get; set; }
        public double? RandomAvalanche { get; set; }
        public double? RandomBlizzard { get; set; }
        public double? RandomColdwave { get; set; }
        public double? RandomCyclone { get; set; }
        public double? RandomDrought { get; set; }
        public double? RandomEarthquake { get; set; }
        public double? RandomFlood { get; set; }
        public double? RandomHeatwave { get; set; }
        public double? RandomHurricane { get; set; }
        public double? RandomInsects { get; set; }
        public double? RandomLandslide { get; set; }
        public double? RandomStorm { get; set; }
        public double? RandomTidalwave { get; set; }
        public double? RandomTornado { get; set; }
        public double? RandomTsunami { get; set; }
        public double? RandomTyphoon { get; set; }
        public double? RandomVolcanic { get; set; }
        public double? RandomWildfire { get; set; }
        public double? RandomStockcrash { get; set; }
        public double? RandomEcoDep { get; set; }
        public double? RandomEcoBoom { get; set; }
        public double? RandomPoorHarv { get; set; }
        public double? RandomBountHarv { get; set; }
        public double? RandomLivestock { get; set; }
        public double? RandomResOre { get; set; }
        public double? RandomResEnergy { get; set; }
        public double? RandomWealth { get; set; }
        public double? RandomEpidemic { get; set; }
        public double? RandomPopBoom { get; set; }
        public double? RandomFamine { get; set; }
        public double? RandomNuclear { get; set; }
        public double? RandomChemical { get; set; }
        public double? RandomIndustrial { get; set; }
        public double? RandomAntiglobal { get; set; }
    }
}