namespace SuperPowerEditor.Base.DataAccess.Entities
{
    public class Relation
    {
        public int? Id { get; set; }
        public double? Country1 { get; set; }
        public double? Country2 { get; set; }
        public double? Country3 { get; set; }
        public double? Country4 { get; set; }
        public double? Country5 { get; set; }
        public double? Country6 { get; set; }
        public double? Country7 { get; set; }
        public double? Country8 { get; set; }
        public double? Country9 { get; set; }
        public double? Country10 { get; set; }
        public double? Country11 { get; set; }
        public double? Country12 { get; set; }
        public double? Country13 { get; set; }
        public double? Country14 { get; set; }
        public double? Country15 { get; set; }
        public double? Country16 { get; set; }
        public double? Country17 { get; set; }
        public double? Country18 { get; set; }
        public double? Country19 { get; set; }
        public double? Country20 { get; set; }
        public double? Country21 { get; set; }
        public double? Country22 { get; set; }
        public double? Country23 { get; set; }
        public double? Country24 { get; set; }
        public double? Country25 { get; set; }
        public double? Country26 { get; set; }
        public double? Country27 { get; set; }
        public double? Country28 { get; set; }
        public double? Country29 { get; set; }
        public double? Country30 { get; set; }
        public double? Country31 { get; set; }
        public double? Country32 { get; set; }
        public double? Country33 { get; set; }
        public double? Country34 { get; set; }
        public double? Country35 { get; set; }
        public double? Country36 { get; set; }
        public double? Country37 { get; set; }
        public double? Country38 { get; set; }
        public double? Country39 { get; set; }
        public double? Country40 { get; set; }
        public double? Country41 { get; set; }
        public double? Country42 { get; set; }
        public double? Country43 { get; set; }
        public double? Country44 { get; set; }
        public double? Country45 { get; set; }
        public double? Country46 { get; set; }
        public double? Country47 { get; set; }
        public double? Country48 { get; set; }
        public double? Country49 { get; set; }
        public double? Country50 { get; set; }
        public double? Country51 { get; set; }
        public double? Country52 { get; set; }
        public double? Country53 { get; set; }
        public double? Country54 { get; set; }
        public double? Country55 { get; set; }
        public double? Country56 { get; set; }
        public double? Country57 { get; set; }
        public double? Country58 { get; set; }
        public double? Country59 { get; set; }
        public double? Country60 { get; set; }
        public double? Country61 { get; set; }
        public double? Country62 { get; set; }
        public double? Country63 { get; set; }
        public double? Country64 { get; set; }
        public double? Country65 { get; set; }
        public double? Country66 { get; set; }
        public double? Country67 { get; set; }
        public double? Country68 { get; set; }
        public double? Country69 { get; set; }
        public double? Country70 { get; set; }
        public double? Country71 { get; set; }
        public double? Country72 { get; set; }
        public double? Country73 { get; set; }
        public double? Country74 { get; set; }
        public double? Country75 { get; set; }
        public double? Country76 { get; set; }
        public double? Country77 { get; set; }
        public double? Country78 { get; set; }
        public double? Country79 { get; set; }
        public double? Country80 { get; set; }
        public double? Country81 { get; set; }
        public double? Country82 { get; set; }
        public double? Country83 { get; set; }
        public double? Country84 { get; set; }
        public double? Country85 { get; set; }
        public double? Country86 { get; set; }
        public double? Country87 { get; set; }
        public double? Country88 { get; set; }
        public double? Country89 { get; set; }
        public double? Country90 { get; set; }
        public double? Country91 { get; set; }
        public double? Country92 { get; set; }
        public double? Country93 { get; set; }
        public double? Country94 { get; set; }
        public double? Country95 { get; set; }
        public double? Country96 { get; set; }
        public double? Country97 { get; set; }
        public double? Country98 { get; set; }
        public double? Country99 { get; set; }
        public double? Country100 { get; set; }
        public double? Country101 { get; set; }
        public double? Country102 { get; set; }
        public double? Country103 { get; set; }
        public double? Country104 { get; set; }
        public double? Country105 { get; set; }
        public double? Country106 { get; set; }
        public double? Country107 { get; set; }
        public double? Country108 { get; set; }
        public double? Country109 { get; set; }
        public double? Country110 { get; set; }
        public double? Country111 { get; set; }
        public double? Country112 { get; set; }
        public double? Country113 { get; set; }
        public double? Country114 { get; set; }
        public double? Country115 { get; set; }
        public double? Country116 { get; set; }
        public double? Country117 { get; set; }
        public double? Country118 { get; set; }
        public double? Country119 { get; set; }
        public double? Country120 { get; set; }
        public double? Country121 { get; set; }
        public double? Country122 { get; set; }
        public double? Country123 { get; set; }
        public double? Country124 { get; set; }
        public double? Country125 { get; set; }
        public double? Country126 { get; set; }
        public double? Country127 { get; set; }
        public double? Country128 { get; set; }
        public double? Country129 { get; set; }
        public double? Country130 { get; set; }
        public double? Country131 { get; set; }
        public double? Country132 { get; set; }
        public double? Country133 { get; set; }
        public double? Country134 { get; set; }
        public double? Country135 { get; set; }
        public double? Country136 { get; set; }
        public double? Country137 { get; set; }
        public double? Country138 { get; set; }
        public double? Country139 { get; set; }
        public double? Country140 { get; set; }
        public double? Country141 { get; set; }
        public double? Country142 { get; set; }
        public double? Country143 { get; set; }
        public double? Country144 { get; set; }
        public double? Country145 { get; set; }
        public double? Country146 { get; set; }
        public double? Country147 { get; set; }
        public double? Country148 { get; set; }
        public double? Country149 { get; set; }
        public double? Country150 { get; set; }
        public double? Country151 { get; set; }
        public double? Country152 { get; set; }
        public double? Country153 { get; set; }
        public double? Country154 { get; set; }
        public double? Country155 { get; set; }
        public double? Country156 { get; set; }
        public double? Country157 { get; set; }
        public double? Country158 { get; set; }
        public double? Country159 { get; set; }
        public double? Country160 { get; set; }
        public double? Country161 { get; set; }
        public double? Country162 { get; set; }
        public double? Country163 { get; set; }
        public double? Country164 { get; set; }
        public double? Country165 { get; set; }
        public double? Country166 { get; set; }
        public double? Country167 { get; set; }
        public double? Country168 { get; set; }
        public double? Country169 { get; set; }
        public double? Country170 { get; set; }
        public double? Country171 { get; set; }
        public double? Country172 { get; set; }
        public double? Country173 { get; set; }
        public double? Country174 { get; set; }
        public double? Country175 { get; set; }
        public double? Country176 { get; set; }
        public double? Country177 { get; set; }
        public double? Country178 { get; set; }
        public double? Country179 { get; set; }
        public double? Country180 { get; set; }
        public double? Country181 { get; set; }
        public double? Country182 { get; set; }
        public double? Country183 { get; set; }
        public double? Country184 { get; set; }
        public double? Country185 { get; set; }
        public double? Country186 { get; set; }
        public double? Country187 { get; set; }
        public double? Country188 { get; set; }
        public double? Country189 { get; set; }
        public double? Country190 { get; set; }
        public double? Country191 { get; set; }
        public double? Country192 { get; set; }
        public double? Country193 { get; set; }
        public double? Country194 { get; set; }
    }
}