namespace SuperPowerEditor.Base.DataAccess.Entities
{
    public class Research
    {
        public double? ExpenseNuclearMissiledamage { get; set; }
        public double? ExpenseNuclearMissilepayload { get; set; }
        public double? ExpenseNuclearMissilepreci { get; set; }
        public double? ExpenseNuclearMissilerange { get; set; }
        public double? ExpenseNuclearSensors { get; set; }
        public double? ExpenseNuclearSpeed { get; set; }
        public double? ExpenseNuclearStealth { get; set; }
        public double? MaxLvlAirArmor { get; set; }
        public double? MaxLvlAirCountermeasures { get; set; }
        public double? MaxLvlAirGundamage { get; set; }
        public double? MaxLvlAirGunprecision { get; set; }
        public double? MaxLvlAirGunrange { get; set; }
        public double? MaxLvlAirMissiledamage { get; set; }
        public double? MaxLvlAirMissilepayload { get; set; }
        public double? MaxLvlAirMissilepreci { get; set; }
        public double? MaxLvlAirMissilerange { get; set; }
        public double? MaxLvlAirSensors { get; set; }
        public double? MaxLvlAirSpeed { get; set; }
        public double? MaxLvlAirStealth { get; set; }
        public double? MaxLvlGroundArmor { get; set; }
        public double? MaxLvlGroundCountermeasures { get; set; }
        public double? MaxLvlGroundGundamage { get; set; }
        public double? MaxLvlGroundGunprecision { get; set; }
        public double? MaxLvlGroundGunrange { get; set; }
        public double? MaxLvlGroundMissiledamage { get; set; }
        public double? MaxLvlGroundMissilepayload { get; set; }
        public double? MaxLvlGroundMissilepreci { get; set; }
        public double? MaxLvlGroundMissilerange { get; set; }
        public double? MaxLvlGroundSensors { get; set; }
        public double? MaxLvlGroundSpeed { get; set; }
        public double? MaxLvlGroundStealth { get; set; }
        public double? MaxLvlNavalArmor { get; set; }
        public double? MaxLvlNavalCountermeasures { get; set; }
        public double? MaxLvlNavalGundamage { get; set; }
        public double? MaxLvlNavalGunprecision { get; set; }
        public double? MaxLvlNavalGunrange { get; set; }
        public double? MaxLvlNavalMissiledamage { get; set; }
        public double? MaxLvlNavalMissilepayload { get; set; }
        public double? MaxLvlNavalMissilepreci { get; set; }
        public double? MaxLvlNavalMissilerange { get; set; }
        public double? MaxLvlNavalSensors { get; set; }
        public double? MaxLvlNavalSpeed { get; set; }
        public double? MaxLvlNavalStealth { get; set; }
        public double? MaxLvlNuclearArmor { get; set; }
        public double? MaxLvlNuclearCountermeasures { get; set; }
        public double? MaxLvlNuclearGundamage { get; set; }
        public double? MaxLvlNuclearGunprecision { get; set; }
        public double? MaxLvlNuclearGunrange { get; set; }
        public double? MaxLvlNuclearMissiledamage { get; set; }
        public double? MaxLvlNuclearMissilepayload { get; set; }
        public double? MaxLvlNuclearMissilepreci { get; set; }
        public double? MaxLvlNuclearMissilerange { get; set; }
        public double? MaxLvlNuclearSensors { get; set; }
        public double? MaxLvlNuclearSpeed { get; set; }
        public double? MaxLvlNuclearStealth { get; set; }
        public int? Id { get; set; }
        public double? ExpenseAir { get; set; }
        public double? ExpenseGround { get; set; }
        public double? ExpenseNaval { get; set; }
        public double? ExpenseNuclear { get; set; }
        public double? ExpenseAirArmor { get; set; }
        public double? ExpenseAirCountermeasures { get; set; }
        public double? ExpenseAirGundamage { get; set; }
        public double? ExpenseAirGunprecision { get; set; }
        public double? ExpenseAirGunrange { get; set; }
        public double? ExpenseAirMissiledamage { get; set; }
        public double? ExpenseAirMissilepayload { get; set; }
        public double? ExpenseAirMissilepreci { get; set; }
        public double? ExpenseAirMissilerange { get; set; }
        public double? ExpenseAirSensors { get; set; }
        public double? ExpenseAirSpeed { get; set; }
        public double? ExpenseAirStealth { get; set; }
        public double? ExpenseGroundArmor { get; set; }
        public double? ExpenseGroundCountermeasures { get; set; }
        public double? ExpenseGroundGundamage { get; set; }
        public double? ExpenseGroundGunprecision { get; set; }
        public double? ExpenseGroundGunrange { get; set; }
        public double? ExpenseGroundMissiledamage { get; set; }
        public double? ExpenseGroundMissilepayload { get; set; }
        public double? ExpenseGroundMissilepreci { get; set; }
        public double? ExpenseGroundMissilerange { get; set; }
        public double? ExpenseGroundSensors { get; set; }
        public double? ExpenseGroundSpeed { get; set; }
        public double? ExpenseGroundStealth { get; set; }
        public double? ExpenseNavalArmor { get; set; }
        public double? ExpenseNavalCountermeasures { get; set; }
        public double? ExpenseNavalGundamage { get; set; }
        public double? ExpenseNavalGunprecision { get; set; }
        public double? ExpenseNavalGunrange { get; set; }
        public double? ExpenseNavalMissiledamage { get; set; }
        public double? ExpenseNavalMissilepayload { get; set; }
        public double? ExpenseNavalMissilepreci { get; set; }
        public double? ExpenseNavalMissilerange { get; set; }
        public double? ExpenseNavalSensors { get; set; }
        public double? ExpenseNavalSpeed { get; set; }
        public double? ExpenseNavalStealth { get; set; }
        public double? ExpenseNuclearArmor { get; set; }
        public double? ExpenseNuclearCountermeasures { get; set; }
        public double? ExpenseNuclearGundamage { get; set; }
        public double? ExpenseNuclearGunprecision { get; set; }
        public double? ExpenseNuclearGunrange { get; set; }
    }
}