namespace SuperPowerEditor.Base.DataAccess.Entities
{
    public class Resources
    {
        public int? Id { get; set; }
        public double? CerealsImport { get; set; }
        public double? CerealsImportDesired { get; set; }
        public double? CerealsExport { get; set; }
        public double? CerealsExportDesired { get; set; }
        public string CerealsGvtCtrl { get; set; }
        public string CerealsLegal { get; set; }
        public string CerealsMeet { get; set; }
        public double? CerealsTaxes { get; set; }
        public double? CerealsGdp { get; set; }
        public double? VegFruitsImport { get; set; }
        public double? VegFruitsImportDesired { get; set; }
        public double? VegFruitsExport { get; set; }
        public double? VegFruitsExportDesired { get; set; }
        public string VegFruitsGvtCtrl { get; set; }
        public string VegFruitsLegal { get; set; }
        public string VegFruitsMeet { get; set; }
        public double? VegFruitsTaxes { get; set; }
        public double? VegFruitsGdp { get; set; }
        public double? MeatImport { get; set; }
        public double? MeatImportDesired { get; set; }
        public double? MeatExport { get; set; }
        public double? MeatExportDesired { get; set; }
        public string MeatGvtCtrl { get; set; }
        public string MeatLegal { get; set; }
        public string MeatMeet { get; set; }
        public double? MeatTaxes { get; set; }
        public double? MeatGdp { get; set; }
        public double? DairyImport { get; set; }
        public double? DairyImportDesired { get; set; }
        public double? DairyExport { get; set; }
        public double? DairyExportDesired { get; set; }
        public string DairyGvtCtrl { get; set; }
        public string DairyLegal { get; set; }
        public string DairyMeet { get; set; }
        public double? DairyTaxes { get; set; }
        public double? DairyGdp { get; set; }
        public double? TobaccoImport { get; set; }
        public double? TobaccoImportDesired { get; set; }
        public double? TobaccoExport { get; set; }
        public double? TobaccoExportDesired { get; set; }
        public string TobaccoGvtCtrl { get; set; }
        public string TobaccoLegal { get; set; }
        public string TobaccoMeet { get; set; }
        public double? TobaccoTaxes { get; set; }
        public double? TobaccoGdp { get; set; }
        public double? DrugsImport { get; set; }
        public double? DrugsImportDesired { get; set; }
        public double? DrugsExport { get; set; }
        public double? DrugsExportDesired { get; set; }
        public string DrugsGvtCtrl { get; set; }
        public string DrugsLegal { get; set; }
        public string DrugsMeet { get; set; }
        public double? DrugsTaxes { get; set; }
        public double? DrugsGdp { get; set; }
        public double? ElectricityImport { get; set; }
        public double? ElectricityImportDesired { get; set; }
        public double? ElectricityExport { get; set; }
        public double? ElectricityExportDesired { get; set; }
        public string ElectricityGvtCtrl { get; set; }
        public string ElectricityLegal { get; set; }
        public string ElectricityMeet { get; set; }
        public double? ElectricityTaxes { get; set; }
        public double? ElectricityGdp { get; set; }
        public double? FossileFuelsImport { get; set; }
        public double? FossileFuelsImportDesired { get; set; }
        public double? FossileFuelsExport { get; set; }
        public double? FossileFuelsExportDesired { get; set; }
        public string FossileFuelsGvtCtrl { get; set; }
        public string FossileFuelsLegal { get; set; }
        public string FossileFuelsMeet { get; set; }
        public double? FossileFuelsTaxes { get; set; }
        public double? FossileFuelsGdp { get; set; }
        public double? WoodPaperImport { get; set; }
        public double? WoodPaperImportDesired { get; set; }
        public double? WoodPaperExport { get; set; }
        public double? WoodPaperExportDesired { get; set; }
        public string WoodPaperGvtCtrl { get; set; }
        public string WoodPaperLegal { get; set; }
        public string WoodPaperMeet { get; set; }
        public double? WoodPaperTaxes { get; set; }
        public double? WoodPaperGdp { get; set; }
        public double? MineralsImport { get; set; }
        public double? MineralsImportDesired { get; set; }
        public double? MineralsExport { get; set; }
        public double? MineralsExportDesired { get; set; }
        public string MineralsGvtCtrl { get; set; }
        public string MineralsLegal { get; set; }
        public string MineralsMeet { get; set; }
        public double? MineralsTaxes { get; set; }
        public double? MineralsGdp { get; set; }
        public double? IronSteelImport { get; set; }
        public double? IronSteelImportDesired { get; set; }
        public double? IronSteelExport { get; set; }
        public double? IronSteelExportDesired { get; set; }
        public string IronSteelGvtCtrl { get; set; }
        public string IronSteelLegal { get; set; }
        public string IronSteelMeet { get; set; }
        public double? IronSteelTaxes { get; set; }
        public double? IronSteelGdp { get; set; }
        public double? PrecStonesImport { get; set; }
        public double? PrecStonesImportDesired { get; set; }
        public double? PrecStonesExport { get; set; }
        public double? PrecStonesExportDesired { get; set; }
        public string PrecStonesGvtCtrl { get; set; }
        public string PrecStonesLegal { get; set; }
        public string PrecStonesMeet { get; set; }
        public double? PrecStonesTaxes { get; set; }
        public double? PrecStonesGdp { get; set; }
        public double? FabricsImport { get; set; }
        public double? FabricsImportDesired { get; set; }
        public double? FabricsExport { get; set; }
        public double? FabricsExportDesired { get; set; }
        public string FabricsGvtCtrl { get; set; }
        public string FabricsLegal { get; set; }
        public string FabricsMeet { get; set; }
        public double? FabricsTaxes { get; set; }
        public double? FabricsGdp { get; set; }
        public double? PlasticsImport { get; set; }
        public double? PlasticsImportDesired { get; set; }
        public double? PlasticsExport { get; set; }
        public double? PlasticsExportDesired { get; set; }
        public string PlasticsGvtCtrl { get; set; }
        public string PlasticsLegal { get; set; }
        public string PlasticsMeet { get; set; }
        public double? PlasticsTaxes { get; set; }
        public double? PlasticsGdp { get; set; }
        public double? ChemicalsImport { get; set; }
        public double? ChemicalsImportDesired { get; set; }
        public double? ChemicalsExport { get; set; }
        public double? ChemicalsExportDesired { get; set; }
        public string ChemicalsGvtCtrl { get; set; }
        public string ChemicalsLegal { get; set; }
        public string ChemicalsMeet { get; set; }
        public double? ChemicalsTaxes { get; set; }
        public double? ChemicalsGdp { get; set; }
        public double? PharmaImport { get; set; }
        public double? PharmaImportDesired { get; set; }
        public double? PharmaExport { get; set; }
        public double? PharmaExportDesired { get; set; }
        public string PharmaGvtCtrl { get; set; }
        public string PharmaLegal { get; set; }
        public string PharmaMeet { get; set; }
        public double? PharmaTaxes { get; set; }
        public double? PharmaGdp { get; set; }
        public double? HhApplImport { get; set; }
        public double? HhApplImportDesired { get; set; }
        public double? HhApplExport { get; set; }
        public double? HhApplExportDesired { get; set; }
        public string HhApplGvtCtrl { get; set; }
        public string HhApplLegal { get; set; }
        public string HhApplMeet { get; set; }
        public double? HhApplTaxes { get; set; }
        public double? HhApplGdp { get; set; }
        public double? VehiculesImport { get; set; }
        public double? VehiculesImportDesired { get; set; }
        public double? VehiculesExport { get; set; }
        public double? VehiculesExportDesired { get; set; }
        public string VehiculesGvtCtrl { get; set; }
        public string VehiculesLegal { get; set; }
        public string VehiculesMeet { get; set; }
        public double? VehiculesTaxes { get; set; }
        public double? VehiculesGdp { get; set; }
        public double? MachineryImport { get; set; }
        public double? MachineryImportDesired { get; set; }
        public double? MachineryExport { get; set; }
        public double? MachineryExportDesired { get; set; }
        public string MachineryGvtCtrl { get; set; }
        public string MachineryLegal { get; set; }
        public string MachineryMeet { get; set; }
        public double? MachineryTaxes { get; set; }
        public double? MachineryGdp { get; set; }
        public double? HhCommImport { get; set; }
        public double? HhCommImportDesired { get; set; }
        public double? HhCommExport { get; set; }
        public double? HhCommExportDesired { get; set; }
        public string HhCommGvtCtrl { get; set; }
        public string HhCommLegal { get; set; }
        public string HhCommMeet { get; set; }
        public double? HhCommTaxes { get; set; }
        public double? HhCommGdp { get; set; }
        public double? LuxuryCommImport { get; set; }
        public double? LuxuryCommImportDesired { get; set; }
        public double? LuxuryCommExport { get; set; }
        public double? LuxuryCommExportDesired { get; set; }
        public string LuxuryCommGvtCtrl { get; set; }
        public string LuxuryCommLegal { get; set; }
        public string LuxuryCommMeet { get; set; }
        public double? LuxuryCommTaxes { get; set; }
        public double? LuxuryCommGdp { get; set; }
        public double? ConstructionImport { get; set; }
        public double? ConstructionImportDesired { get; set; }
        public double? ConstructionExport { get; set; }
        public double? ConstructionExportDesired { get; set; }
        public string ConstructionGvtCtrl { get; set; }
        public string ConstructionLegal { get; set; }
        public string ConstructionMeet { get; set; }
        public double? ConstructionTaxes { get; set; }
        public double? ConstructionGdp { get; set; }
        public double? EngineeringImport { get; set; }
        public double? EngineeringImportDesired { get; set; }
        public double? EngineeringExport { get; set; }
        public double? EngineeringExportDesired { get; set; }
        public string EngineeringGvtCtrl { get; set; }
        public string EngineeringLegal { get; set; }
        public string EngineeringMeet { get; set; }
        public double? EngineeringTaxes { get; set; }
        public double? EngineeringGdp { get; set; }
        public double? HealthCareImport { get; set; }
        public double? HealthCareImportDesired { get; set; }
        public double? HealthCareExport { get; set; }
        public double? HealthCareExportDesired { get; set; }
        public string HealthCareGvtCtrl { get; set; }
        public string HealthCareLegal { get; set; }
        public string HealthCareMeet { get; set; }
        public double? HealthCareTaxes { get; set; }
        public double? HealthCareGdp { get; set; }
        public double? RetailImport { get; set; }
        public double? RetailImportDesired { get; set; }
        public double? RetailExport { get; set; }
        public double? RetailExportDesired { get; set; }
        public string RetailGvtCtrl { get; set; }
        public string RetailLegal { get; set; }
        public string RetailMeet { get; set; }
        public double? RetailTaxes { get; set; }
        public double? RetailGdp { get; set; }
        public double? LegalServImport { get; set; }
        public double? LegalServImportDesired { get; set; }
        public double? LegalServExport { get; set; }
        public double? LegalServExportDesired { get; set; }
        public string LegalServGvtCtrl { get; set; }
        public string LegalServLegal { get; set; }
        public string LegalServMeet { get; set; }
        public double? LegalServTaxes { get; set; }
        public double? LegalServGdp { get; set; }
        public double? MarketAdImport { get; set; }
        public double? MarketAdImportDesired { get; set; }
        public double? MarketAdExport { get; set; }
        public double? MarketAdExportDesired { get; set; }
        public string MarketAdGvtCtrl { get; set; }
        public string MarketAdLegal { get; set; }
        public string MarketAdMeet { get; set; }
        public double? MarketAdTaxes { get; set; }
        public double? MarketAdGdp { get; set; }
    }
}